# Model
save_model: true # Save model after training
model_name: human_policy   # Name of saved model
save_model_path: ./models/il # Path to save model
save_data_path: ./data_il/train_no_tl # Path to save training data

# Train
total_samples: 2_000_000 # Number of obs-act-next_obs-done pairs to generate
net_arch: [128, 64] # Network architecture
